on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'package.json'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: ['18.x', '20.x']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Try to build
        run: npm run build
      - name: Run application
        run: npm start -- -s

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test.ci
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
      - name: Generate Code Coverage report
        id: code-coverage
        uses: barecheck/code-coverage-action@v1
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          barecheck-api-key: ${{ secrets.BARECHECK_API_KEY }}
          lcov-file: './coverage/lcov.info'
          send-summary-comment: ${{ vars.COVERAGE_COMMENT == 'true' }}
          show-annotations: ${{ vars.COVERAGE_ANNOTATIONS }}
